{{- $data := include "consolecrypt-server.secretData" . | fromYaml }}
{{- if $data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consolecrypt-server.secretName" . }}
  labels:
    {{- include "consolecrypt-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
data:
  {{- range $k, $v := $data }}
  {{ $k }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
{{- end }}
